version: 2
updates:

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: develop
    schedule:
      interval: "daily"

  - package-ecosystem: maven
    directory: "/"
    target-branch: develop
    schedule:
      interval: "daily"
