
name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        lombok-version: ["1.18.16"]
        java-version: [7, 8, 11, 14]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - name: Cache Maven Packages
        uses: actions/cache@v2
        with:
          # be careful not to include ~/.m2/settings.xml which contains credentials
          path: |
            ~/.m2/repository
            ~/.m2/wrapper
          key: m2-tests-${{ hashFiles('**/pom.xml', '.mvn/*.xml') }}
          restore-keys: |
            m2-tests
            m2

      - name: Initialize
        run: bash mvnw initialize -B

      - name: Build & Test
        run: bash mvnw clean install -B

      - name: Test Spring Boot Example
        run:  bash mvnw clean install -B -f lombok-presence-checker-example/pom.xml
        if: matrix.java-version != 7
