
name: Release

on:
  release:
    types:
      - published

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 8

      - name: Set up Maven settings.xml to access Sonatype Nexus
        run: |
          echo '
            <settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
              <servers>
                <server>
                  <id>ossrh</id>
                  <username>${{ secrets.SONATYPE_USER }}</username>
                  <password>${{ secrets.SONATYPE_PASSWORD }}</password>
                </server>
              </servers>
            </settings>
          ' > ~/.m2/settings.xml

      - name: Set up GPG keys
        run: |
          mkdir .gpg
          echo '${{ secrets.GPG_PRIVATE_KEY }}' > .gpg/private_key.gpg
          gpg --import .gpg/private_key.gpg
          rm -rf .gpg

      - name: Initialize
        run: bash mvnw -B initialize

      - name: Install
        run: bash mvnw -B clean install

      - name: Release
        run: bash mvnw -B clean deploy -Prelease -pl '!lombok-unshaded'
