
name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        lombok-version: ["1.18.16"]
        java-version: [8, 11, 14]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java-version }}

      - name: Initialize
        run: bash mvnw initialize -B

      - name: Build & Test
        run: bash mvnw clean install -B

      - name: Test Spring Boot Example
        run:  bash mvnw clean install -B -f lombok-presence-checker-example/pom.xml
        if: matrix.java-version != 7
